[[redirects]]
  from = "/wing/24life/*"
  to = "https://hirarira.net/wwa/24life/:splat"

[[redirects]]
  from = "/wing/kuso6.html"
  to = "https://hirarira.net/wwa/kuso/kuso06/"

[[redirects]]
  from = "/wing/spaceisland.html"
  to = "https://hirarira.net/wwa/bcdwwa/spaceisland/"

# ヒラリラーのMP WWAページからの遷移対応 (拡張子が抜けている + 大文字小文字違い)
[[redirects]]
  from = "/wing/24life/24life"
  to = "https://archive.chashitsu.org/wing/24LIFE/24LIFE.html"

# ヒラリラーのMP WWAページからの遷移対応 (拡張子が抜けている + 大文字小文字違い)
[[redirects]]
  from = "/wing/moneyxp"
  to = "https://archive.chashitsu.org/wing/moneyXP.html"

[[redirects]]
  from ="/wing/moneyxp.html"
  to = "https://hirarira.net/wwa/ssawwa/moneyxp/"

[[redirects]]
  from ="/wing/seikatsu.html"
  to = "https://hirarira.net/wwa/ssawwa/seikatsu/"

[[redirects]]
  from = "/wing/kuso6"
  to = "https://hirarira.net/wwa/kuso/kuso06/"

[[redirects]]
  from = "/wing/spaceisland"
  to = "https://hirarira.net/wwa/bcdwwa/spaceisland/"

[[redirects]]
  from ="/wing/moneyxp"
  to = "https://hirarira.net/wwa/ssawwa/moneyxp/"

[[redirects]]
  from ="/wing/seikatsu"
  to = "https://hirarira.net/wwa/ssawwa/seikatsu/"

[[redirects]]
  from = "/*"
  to = "https://archive.chashitsu.org/:splat"
